# Generated by Django 5.1.5 on 2025-01-19 07:57

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('answer_text', models.CharField(max_length=500)),
                ('valid_range', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriviaSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TriviaTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TriviaQuestionSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='triviabackend.triviaquestion')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='triviabackend.triviasubject')),
            ],
        ),
        migrations.CreateModel(
            name='TriviaQuestionConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='triviabackend.triviaquestion')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='triviabackend.triviasubject')),
            ],
        ),
        migrations.CreateModel(
            name='TriviaQuestionTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='triviabackend.triviaquestion')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='triviabackend.triviatopic')),
            ],
        ),
    ]
