# Generated by Django 5.1.5 on 2025-01-20 12:38

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triviabackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaquestion',
            name='valid_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(null=True),
        ),
    ]
