# Generated by Django 5.1.5 on 2025-01-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triviabackend', '0002_alter_triviaquestion_valid_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
